/*
 * This file is auto-generated by ./bin/rails stimulus:manifest:update
 * Run that command whenever you add a new controller or create them with
 * ./bin/rails generate stimulus controllerName
 */

import {application} from "./application";

import DeckTypeController from "./deck_type_controller";
application.register("deck-type", DeckTypeController);

import DialogController from "./dialog_controller";
application.register("dialog", DialogController);

import FileUploadController from "./file_upload_controller";
application.register("file-upload", FileUploadController);

import HotkeysController from "./hotkeys_controller";
application.register("hotkeys", HotkeysController);

import MobileNavController from "./mobile_nav_controller";
application.register("mobile-nav", MobileNavController);

import MusicStudyController from "./music_study_controller";
application.register("music-study", MusicStudyController);
