// This configuration was generated by `exe/eslint_autogen`
// on 2026-07-07 04:24:21 UTC.
// The point is for the user to remove these configuration records
// one by one as the offenses are removed from the code base.

import type {Linter} from "eslint";

const config: Linter.Config[] = [
  // Offense count: 1
  {
    files: [
      "spec/javascript/controllers/fuzzy_find_controller_spec.ts",
    ],
    rules: {
      "max-lines": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "app/javascript/controllers/confirm_submit_controller.ts",
    ],
    rules: {
      "no-alert": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "app/javascript/application.ts",
    ],
    rules: {
      "no-void": "off",
    },
  },
  // Offense count: 3
  {
    files: [
      "spec/javascript/controllers/music_study_controller_inactivity_spec.ts",
      "spec/javascript/controllers/music_study_controller_spec.ts",
      "spec/javascript/controllers/music_study_controller_ticks_spec.ts",
    ],
    rules: {
      "vitest/no-hooks": "off",
    },
  },
  // Offense count: 3
  {
    files: [
      "spec/javascript/controllers/music_study_controller_inactivity_spec.ts",
    ],
    rules: {
      "vitest/prefer-called-with": "off",
    },
  },
  // Offense count: 4
  {
    files: [
      "spec/javascript/controllers/music_study_controller_spec.ts",
      "spec/javascript/controllers/music_study_controller_ticks_spec.ts",
    ],
    rules: {
      "vitest/prefer-import-in-mock": "off",
    },
  },
  // Offense count: 4
  {
    files: [
      "spec/javascript/controllers/dialog_controller_spec.ts",
      "spec/javascript/setup.ts",
    ],
    rules: {
      "vitest/require-hook": "off",
    },
  },
  // Offense count: 1
  {
    files: [
      "spec/javascript/setup.ts",
    ],
    rules: {
      "vitest/require-mock-type-parameters": "off",
    },
  },
];

export default config;
