// This configuration was generated by `exe/eslint_autogen`
// on 2026-02-13 00:31:54 UTC.
// The point is for the user to remove these configuration records
// one by one as the offenses are removed from the code base.

import type {Linter} from "eslint";

const config: Linter.Config[] = [
  // Offense count: 1
  {
    files: [
      "spec/javascript/controllers/file_upload_controller_spec.ts",
    ],
    rules: {
      "@typescript-eslint/consistent-type-assertions": "off",
    },
  },
];

export default config;
